config/routes.rb
Rails.application.routes.draw do
  resources :photos
  resources :rolls
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :roll
end

app/models/roll.rb
class Roll < ApplicationRecord
  has_many :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: %i[ show edit update destroy ]

  # GET /photos or /photos.json
  def index

    @photos = Photo.all
    @photos = @photos.sort_by {|photo| photo.roll_id}

    # This shows only photos from roll2 but is hardcoded. Need to work out how
    # to pass the id of the current Roll to photos_controller to make it dynamic
    #@photos = Photo.all.select do |x|
    #  x.roll_id == 2 #params[:index_roll_id]
    #end
  end

  # GET /photos/1 or /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos or /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: "Photo was successfully created." }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1 or /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: "Photo was successfully updated." }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1 or /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: "Photo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def photo_params
      params.require(:photo).permit(:aperture, :shutter, :iso, :notes,:roll_id)
    end
end

app/controllers/rolls_controller.rb
class RollsController < ApplicationController
  before_action :set_roll, only: %i[ show edit update destroy ]

  # GET /rolls or /rolls.json
  def index
    @rolls = Roll.all
  end

  # GET /rolls/1 or /rolls/1.json
  def show
  end

  # GET /rolls/new
  def new
    @roll = Roll.new
  end

  # GET /rolls/1/edit
  def edit
  end

  # POST /rolls or /rolls.json
  def create
    @roll = Roll.new(roll_params)

    respond_to do |format|
      if @roll.save
        format.html { redirect_to @roll, notice: "Roll was successfully created." }
        format.json { render :show, status: :created, location: @roll }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @roll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rolls/1 or /rolls/1.json
  def update
    respond_to do |format|
      if @roll.update(roll_params)
        format.html { redirect_to @roll, notice: "Roll was successfully updated." }
        format.json { render :show, status: :ok, location: @roll }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @roll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rolls/1 or /rolls/1.json
  def destroy
    @roll.destroy
    respond_to do |format|
      format.html { redirect_to rolls_url, notice: "Roll was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_roll
      @roll = Roll.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def roll_params
      params.require(:roll).permit(:start, :end, :stock, :format, :iso, :push, :current, :dev, :scan, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/rolls_helper.rb
module RollsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnalogExif</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Analog Exif v1.0</h1>
    <%= yield %>
  </body>
</html>

app/views/photos/_form.html.erb
<%= form_with(model: photo) do |form| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
        <% photo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%=form.label :roll %>
    <%=form.text_field :roll_id %>

  <div class="field">
    <%= form.label :shutter %>
    <%= form.text_field :shutter %>
  </div>

  <div class="field">
    <%= form.label :aperture %>
    <%= form.text_field :aperture %>
  </div>

  <div class="field">
    <%= form.label :iso %>
    <%= form.text_field :iso %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Photos</h1>

<table>
  <thead>
    <tr>
      <th>Photo ID</th>
      <th>Roll ID</th>
      <th>Shutter</th>
      <th>Aperture</th>
      <th>Iso</th>
      <th>Notes</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <% if (photo.roll_id%2 == 0) %>
        <tr style="background-color:#CCE6FF">
      <% else %>
      <tr>
      <% end %>
        <td><%= photo.id %></td>
        <td><%= photo.roll_id %></td>
        <td><%= photo.shutter %></td>
        <td><%= photo.aperture %></td>
        <td><%= photo.iso %></td>
        <td><%= photo.notes %></td>
        <td><%= link_to 'Show', photo %></td>
        <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
        <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photo', new_photo_path, class:"submit-button" %>
<br>
<%= link_to 'Back', rolls_path, class:"submit-button" %>

app/views/photos/new.html.erb
<h1>New Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Shutter:</strong>
  <%= @photo.shutter %>
</p>

<p>
  <strong>Aperture:</strong>
  <%= @photo.aperture %>
</p>

<p>
  <strong>Iso:</strong>
  <%= @photo.iso %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @photo.notes %>
</p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>

app/views/rolls/_form.html.erb
<%= form_with(model: roll) do |form| %>
  <% if roll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(roll.errors.count, "error") %> prohibited this roll from being saved:</h2>

      <ul>
        <% roll.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :start %>
    <%= form.date_select :start %>
  </div>

  <div class="field">
    <%= form.label :end %>
    <%= form.date_select :end %>
  </div>

  <div class="field">
    <%= form.label :stock %>
    <%= form.text_field :stock %>
  </div>

  <div class="field">
    <%= form.label :format %>
    <%= form.text_field :format %>
  </div>

  <div class="field">
    <%= form.label :iso %>
    <%= form.text_field :iso %>
  </div>

  <div class="field">
    <%= form.label :push %>
    <%= form.text_field :push %>
  </div>

  <div class="field">
    <%= form.label :current %>
    <%= form.check_box :current %>
  </div>

  <div class="field">
    <%= form.label :dev %>
    <%= form.check_box :dev %>
  </div>

  <div class="field">
    <%= form.label :scan %>
    <%= form.check_box :scan %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rolls/edit.html.erb
<h1>Editing Roll</h1>

<%= render 'form', roll: @roll %>

<%= link_to 'Show', @roll %> |
<%= link_to 'Back', rolls_path %>

app/views/rolls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rolls</h1>

<table style= "width:70%">
  <thead>
    <tr>
      <th style="width:5%">Roll ID</th>
      <th style="width:10%">Start</th>
      <th style="width:10%">End</th>
      <th>Stock</th>
      <th>Format</th>
      <th>Iso</th>
      <th>Push</th>
      <th style="width:6%">Current</th>
      <th style="width:6%">Dev</th>
      <th style="width:6%">Scan</th>
      <th style="width:20%">Notes</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @rolls.each do |roll| %>
      <tr>
        <td><%= roll.id %></td>
        <td><%= roll.start %></td>
        <td><%= roll.end %></td>
        <td><%= roll.stock %></td>
        <td><%= roll.format %></td>
        <td><%= roll.iso %></td>
        <td><%= roll.push %></td>
        <% if roll.current %>
          <td style="background-color:green"></td>
        <% else %>
          <td style="background-color:red"></td>
        <% end %>
        <% if roll.dev %>
          <td style="background-color:green"></td>
        <% else %>
          <td style="background-color:red"></td>
        <% end %>
        <% if roll.scan %>
          <td style="background-color:green"></td>
        <% else %>
          <td style="background-color:red"></td>
        <% end %>
        <td><%= roll.notes %></td>
        <td><%= link_to 'Show', roll %></td>
        <td><%= link_to 'Edit', edit_roll_path(roll) %></td>
        <td><%= link_to 'Destroy', roll, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Roll', new_roll_path, class:"submit-button" %>
<br>
<%= link_to 'New Photo', new_photo_path, class:"submit-button" %>

app/views/rolls/new.html.erb
<h1>New Roll</h1>

<%= render 'form', roll: @roll %>

<%= link_to 'Back', rolls_path %>

app/views/rolls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start:</strong>
  <%= @roll.start %>
</p>

<p>
  <strong>End:</strong>
  <%= @roll.end %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @roll.stock %>
</p>

<p>
  <strong>Format:</strong>
  <%= @roll.format %>
</p>

<p>
  <strong>Iso:</strong>
  <%= @roll.iso %>
</p>

<p>
  <strong>Push:</strong>
  <%= @roll.push %>
</p>

<p>
  <strong>Current:</strong>
  <%= @roll.current %>
</p>

<p>
  <strong>Dev:</strong>
  <%= @roll.dev %>
</p>

<p>
  <strong>Scan:</strong>
  <%= @roll.scan %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @roll.notes %>
</p>

<%= link_to 'Edit', edit_roll_path(@roll) %>
<%= link_to 'Show Photos', photos_path %>
<%= link_to 'Back', rolls_path %>